In [44]:
import pandas as pd
df = pd.read_csv(r"D:\Application\AhhShootHereWeGoAgain\ecommerce-revenue-delivery-retention-analysis\data\raw\olist_customers_dataset.csv")

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [46]:
df.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [47]:
df.duplicated().sum()

np.int64(0)

In [48]:
df["customer_unique_id"].duplicated().sum()

np.int64(3345)

In [49]:
df["customer_id"].duplicated().sum()

np.int64(0)

In [50]:
df[df["customer_unique_id"].duplicated()].head(10)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
679,c57b4b6f3719475543b721e720a526ad,b6c083700ca8c135ba9f0f132930d4e8,8686,suzano,SP
1463,9f6f3da49e2d46e3a7529f5e3c25ecce,a40096fc0a3862e9e12bc55b5f8e6ab2,20561,rio de janeiro,RJ
1607,299f7b5125c8fbe1761a1b320c34fc7d,b8b3c435a58aebd788a477bed8342910,95585,arroio do sal,RS
2811,226d59f9f4b98e228b689eea45d03a6d,66980c3775537536f77b434d74e520f5,30290,belo horizonte,MG
3198,b1253701171dfb298f52a221f824e45b,788313d21c3507fe890921f6e17aa679,11070,santos,SP
3640,b59240e14630c3dad40626dcdaf69b18,5faabfe6772088c4d906b63fa81ac63d,95047,caxias do sul,RS
3792,c9f8da8278a23eb777ede2591b9ad3ee,c2551ea089b7ebbc67a2ea8757152514,44380,cruz das almas,BA
4990,8b9ae8a8961bb6ca3fa720d5a726da83,67626c49069bdf05ff127d59a6649948,88348,camboriu,SC
5466,d70f1b062700147c365624d85570779f,8bb910cd8c3b29e4acf2e94e3aaffbbf,78005,cuiaba,MT
6129,a4413edae691fd0d28bd04b8a38b259d,3e43e6105506432c953e165fb2acf44c,11700,praia grande,SP

In [51]:
df[df["customer_unique_id"]=="b6c083700ca8c135ba9f0f132930d4e8"]

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
132,f7c5afab273b47ab517e096e0219b932,b6c083700ca8c135ba9f0f132930d4e8,8686,suzano,SP
679,c57b4b6f3719475543b721e720a526ad,b6c083700ca8c135ba9f0f132930d4e8,8686,suzano,SP