In [89]:
import pandas as pd
df = pd.read_csv(r"D:\Application\AhhShootHereWeGoAgain\ecommerce-revenue-delivery-retention-analysis\data\raw\olist_order_reviews_dataset.csv")

In [90]:
df.shape

(99224, 7)

In [91]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [92]:
df.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [93]:
df.duplicated().sum()

np.int64(0)

In [94]:
df["review_id"].duplicated().sum()

np.int64(814)

In [95]:
df[df["review_id"].duplicated()].head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
3317,3242cc306a9218d0377831e175d62fbf,9c5bfba7de6a4abbb6ba0baab78d1622,5,NaN,Ótimo,2017-07-21 00:00:00,2017-07-22 01:06:37
5719,308316408775d1600dad81bd3184556d,3fe4dbcdb046a475dbf25463c1ca78bd,5,NaN,Ajudem a rastrear uma das 3 prateleiras que fa...,2017-09-07 00:00:00,2017-09-11 09:58:09
7213,8ee90ac383cf825bb7f4756130d4e74a,75d5d3d16567a27eefc5752aeb063072,5,NaN,recomendo,2017-05-30 00:00:00,2017-06-02 18:16:17
7805,d433c252647c51309432ca0b763f969b,191abde9c3bf77d1ce67d100d8db6d15,1,NaN,NaN,2017-09-03 00:00:00,2017-09-06 16:11:00
9013,03a6a25db577d0689440933055111897,3fde8b7313af6b37b84b5c7594d7add0,5,NaN,Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...,2017-12-15 00:00:00,2017-12-16 01:32:18

In [96]:
df[df["review_id"]=="03a6a25db577d0689440933055111897"]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
1988,03a6a25db577d0689440933055111897,2acfdc5131ff2cf4433e668454c9784c,5,NaN,Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...,2017-12-15 00:00:00,2017-12-16 01:32:18
9013,03a6a25db577d0689440933055111897,3fde8b7313af6b37b84b5c7594d7add0,5,NaN,Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...,2017-12-15 00:00:00,2017-12-16 01:32:18

In [97]:
df.groupby("review_id")["order_id"].nunique().loc[lambda x:x<2]

review_id
0001239bc1de2e33cb583967c2ca4c67    1
0001cc6860aeaf5b9017fe4131a52e62    1
00020c7512a52e92212f12d3e37513c0    1
00032b0141443497c898b3093690af51    1
00034d88989f9a4c393bdcaec301537f    1
                                   ..
fffcfa6087cd3b651c68252342f13cb9    1
fffd24e2cf1ca4ee917e2f05be3c01fb    1
fffd68e8a9fb73a56a2f504011b0f1f1    1
fffee432d53abd67b5b0fd4fc290d8c3    1
fffefe7a48d22f7b32046421062219d1    1
Name: order_id, Length: 97621, dtype: int64